### ISSUE TITLE
Support for custom colors for jupyterhub theme

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub-jupyterhub-theme#3]
Users need a convenient way to control the:
  - primary
  - secondary
  - text color
  - accent color

**Comment by tonyfast** [comment]
there are currently 6 colors used in the template:
#652e8e #474173 #957da6 #e8e8e8 #00a3b0 #32c544

these colors will have to be ordered according to how the present.

currently the style sheets are outside the templates directory, but to configure them they'll need to be templates, i think.

**Comment by costrouc** [comment]
@tonyfast yes they will need to be in `templates`. I think `templates/page.html`. https://github.com/Quansight/qhub-jupyterhub-theme/blob/master/custom/css/style.css is short and could just be inlined into `templates/page.html`

**Comment by costrouc** [comment]
Re-assigning @tylerpotts to issue.
